
[[plugins]]
repo = 'Shougo/dein.vim'

# vimhelpの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 置換前に結果の表示
[[plugins]]
repo = 'markonm/traces.vim'

# Google翻訳
[[plugins]]
repo = 'skanehira/translate.vim'

# 日本語整形
[[plugins]]
repo = 'fuenor/JpFormat.vim'

# color tableの表示, :XtermColorTableで表示してくれる
[[plugins]]
repo = 'guns/xterm-color-table.vim'

# fzf
[[plugins]]
repo = 'junegunn/fzf.vim'

# /や?での検索でmigemoが使えるようになる
[[plugins]]
repo = 'rhysd/migemo-search.vim'

# f検索が高速に+migemoが使えるようになる
[[plugins]]
repo = 'rhysd/clever-f.vim'






